Make `no_flax.FlaxNotInstalled` a proper `types.ModuleType`.
In Python 3.13 some module attributes (e.g. `__spec__` from PEP 451) are
expected to exist on imported modules. This was triggering an `ImportError`
when running `import haiku as hk` without Flax installed.

```
Traceback (most recent call last):
  File "haiku/_src/no_flax_test.py", line 42, in test_import_shim
    import haiku as hk  # pylint: disable=g-bad-import-order,g-import-not-at-top
    ^^^^^^^^^^^^^^^^^^
  File "haiku/__init__.py", line 20, in <module>
    from haiku import experimental
  File "haiku/experimental/__init__.py", line 66, in <module>
    from haiku.experimental import flax
  File "haiku/_src/no_flax.py", line 24, in __getattr__
    raise ImportError(
        '`haiku.experimental.flax` features require `flax` to be installed.'
    )
ImportError: `haiku.experimental.flax` features require `flax` to be installed.
```
PiperOrigin-RevId: 808487799