Improve shape mismatch error when jax_default_prng_impl has been set.
```
ValueError: Provided key did not have expected shape and/or dtype: expected=(shape=(4,), dtype=uint32), actual=(shape=(2,), dtype=uint32)
Hint: jax_default_prng_impl has been set to 'rbg', the shape mismatch might be because a jax.random.PRNGKey was created before this flag was set.
```
PiperOrigin-RevId: 441743249