Use jax.numpy instead of numpy to use `at` method
This fixes the error:
File "./dm-haiku/examples/rnn/train.py", line 117, in sample
    tokens = tokens.at[0].set(first_token)
AttributeError: 'numpy.ndarray' object has no attribute 'at'